[project]
name = "bigquery-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-bigquery>=1.10.0",
    "dbt-core>=1.10.4",
    "pre-commit>=4.2.0",
    "sqlfluff>=3.4.2",
]
